<?xml version="1.0" encoding="UTF-8"?><dictionary case_sensitive="false">
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
</entry>
<entry count="2">
<token>Autodesk.DesignScript.Geometry.Rectangle,ToString</token>
<token>Autodesk.DesignScript.Geometry.Rectangle,ToString</token>
</entry>
<entry count="432">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Plane,ToString</token>
<token>Autodesk.DesignScript.Geometry.Plane,ToString</token>
</entry>
<entry count="64">
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
</entry>
<entry count="8">
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Cross</token>
<token>Autodesk.DesignScript.Geometry.Vector,Dot</token>
</entry>
<entry count="432">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="8">
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Cross</token>
</entry>
<entry count="108">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="216">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
<token>Autodesk.DesignScript.Geometry.Vector,Cross</token>
</entry>
<entry count="14">
<token>Autodesk.DesignScript.Geometry.UV,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.UV,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.UV,ByCoordinates</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
</entry>
<entry count="10">
<token>Autodesk.DesignScript.Geometry.UV,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.UV,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.UV,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.UV,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.UV,ByCoordinates</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Plane,ToString</token>
<token>Autodesk.DesignScript.Geometry.Plane,ToString</token>
<token>Autodesk.DesignScript.Geometry.Rectangle,ToString</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="216">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="8">
<token>Autodesk.DesignScript.Geometry.Vector,Cross</token>
<token>Autodesk.DesignScript.Geometry.Vector,Dot</token>
<token>Autodesk.DesignScript.Geometry.Vector,Dot</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.Surface,ByLoft</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
<token>Autodesk.DesignScript.Geometry.Vector,Cross</token>
</entry>
<entry count="108">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="2">
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.Surface,ByLoft</token>
</entry>
<entry count="108">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="216">
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
</entry>
<entry count="64">
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
</entry>
<entry count="4">
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
</entry>
<entry count="864">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
</entry>
<entry count="54">
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
<token>Autodesk.DesignScript.Geometry.Vector,Cross</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Plane,ToString</token>
<token>Autodesk.DesignScript.Geometry.Rectangle,ToString</token>
<token>Autodesk.DesignScript.Geometry.Rectangle,ToString</token>
</entry>
<entry count="108">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
</entry>
<entry count="216">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
</entry>
<entry count="432">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="64">
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
</entry>
<entry count="2">
<token>Autodesk.DesignScript.Geometry.Vector,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Vector,Add</token>
<token>Autodesk.DesignScript.Geometry.Vector,Scale</token>
</entry>
<entry count="8">
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Cross</token>
<token>Autodesk.DesignScript.Geometry.Vector,Dot</token>
<token>Autodesk.DesignScript.Geometry.Vector,Dot</token>
</entry>
<entry count="4">
<token>Autodesk.DesignScript.Geometry.Vector,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Vector,ByCoordinates</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.Surface,ByLoft</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
</entry>
<entry count="432">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Solid,ToString</token>
<token>Autodesk.DesignScript.Geometry.Solid,ToString</token>
</entry>
<entry count="8">
<token>Autodesk.DesignScript.Geometry.Vector,Cross</token>
<token>Autodesk.DesignScript.Geometry.Vector,Dot</token>
</entry>
<entry count="8">
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Cross</token>
<token>Autodesk.DesignScript.Geometry.Vector,Dot</token>
</entry>
<entry count="108">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.HostFactory,StartUp</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
</entry>
<entry count="54">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="464">
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="54">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="54">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Surface,ToString</token>
<token>Autodesk.DesignScript.Geometry.Surface,ToString</token>
</entry>
<entry count="216">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="108">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.HostFactory,StartUp</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
</entry>
<entry count="2">
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.Surface,ByLoft</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
</entry>
<entry count="8">
<token>Autodesk.DesignScript.Geometry.Vector,Dot</token>
<token>Autodesk.DesignScript.Geometry.Vector,Dot</token>
</entry>
<entry count="8">
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Cross</token>
<token>Autodesk.DesignScript.Geometry.Vector,Dot</token>
<token>Autodesk.DesignScript.Geometry.Vector,Dot</token>
</entry>
<entry count="54">
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
<token>Autodesk.DesignScript.Geometry.Vector,Cross</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.HostFactory,StartUp</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
</entry>
<entry count="648">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="64">
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.HostFactory,StartUp</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.Surface,ByLoft</token>
</entry>
<entry count="8">
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Circle,ByCenterPointRadius</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Plane,ToString</token>
<token>Autodesk.DesignScript.Geometry.Plane,ToString</token>
<token>Autodesk.DesignScript.Geometry.Rectangle,ToString</token>
<token>Autodesk.DesignScript.Geometry.Rectangle,ToString</token>
</entry>
<entry count="216">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.Surface,ByLoft</token>
</entry>
<entry count="216">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Rectangle,ByWidthLength</token>
<token>Autodesk.DesignScript.Geometry.Surface,ByPatch</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
</entry>
<entry count="108">
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="2">
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.Surface,ByLoft</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.HostFactory,ShutDown</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Point,ToString</token>
<token>Autodesk.DesignScript.Geometry.Solid,ToString</token>
</entry>
<entry count="108">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="108">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="216">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
</entry>
<entry count="216">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
</entry>
<entry count="2">
<token>Autodesk.DesignScript.Geometry.Surface,ByLoft</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.HostFactory,ShutDown</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Plane,ToString</token>
<token>Autodesk.DesignScript.Geometry.Rectangle,ToString</token>
</entry>
<entry count="2">
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.Surface,ByLoft</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
</entry>
<entry count="108">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.HostFactory,StartUp</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
</entry>
<entry count="216">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
</entry>
<entry count="8">
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
</entry>
<entry count="54">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="64">
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
</entry>
<entry count="108">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
</entry>
<entry count="8">
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
</entry>
<entry count="2">
<token>Autodesk.DesignScript.Geometry.Vector,Add</token>
<token>Autodesk.DesignScript.Geometry.Vector,Scale</token>
</entry>
<entry count="64">
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
</entry>
<entry count="2">
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
</entry>
<entry count="108">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="432">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="2">
<token>Autodesk.DesignScript.Geometry.Vector,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Vector,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Vector,ByCoordinates</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Normalized</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
</entry>
<entry count="216">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="2">
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.Surface,ByLoft</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.HostFactory,ShutDown</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
</entry>
<entry count="2">
<token>Autodesk.DesignScript.Geometry.Surface,ByLoft</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
</entry>
<entry count="18">
<token>Autodesk.DesignScript.Geometry.UV,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.UV,ByCoordinates</token>
</entry>
<entry count="108">
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Line,ByStartPointEndPoint</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
</entry>
<entry count="2">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.HostFactory,ShutDown</token>
</entry>
<entry count="12">
<token>Autodesk.DesignScript.Geometry.UV,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.UV,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.UV,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.UV,ByCoordinates</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.HostFactory,StartUp</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Point,ByCoordinates</token>
</entry>
<entry count="2">
<token>Autodesk.DesignScript.Geometry.Vector,ByCoordinates</token>
<token>Autodesk.DesignScript.Geometry.Vector,Add</token>
</entry>
<entry count="2">
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.Surface,ByLoft</token>
</entry>
<entry count="436">
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
</entry>
<entry count="64">
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
<token>Autodesk.DesignScript.Geometry.Geometry,IsAlmostEqualTo</token>
</entry>
<entry count="32">
<token>Autodesk.DesignScript.Geometry.Geometry,DistanceTo</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
<token>Autodesk.DesignScript.Geometry.Point,AsVector</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.HostFactory,StartUp</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
</entry>
<entry count="1">
<token>Autodesk.DesignScript.Geometry.HostFactory,StartUp</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.NurbsCurve,ByControlPoints</token>
<token>Autodesk.DesignScript.Geometry.Surface,ByLoft</token>
<token>Autodesk.DesignScript.Geometry.Surface,PointAtParameter</token>
</entry>
<entry count="8">
<token>Autodesk.DesignScript.Geometry.Vector,Subtract</token>
<token>Autodesk.DesignScript.Geometry.Vector,Cross</token>
</entry>
</dictionary>
